id: A84A4A743
title: Aspiration Prayer of the Ultimate Definitive Meaning
type: translation
pechas:
- I22C499C1
- I48D1CF44
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:44:55.300616
  last_modified_at: 2023-01-04 11:44:55.300629
  collections:
  - Dolpopa Sherab Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  I22C499C1/59B1: 6A00
  I48D1CF44/D00A: 6A00
